open HolKernel Parse boolLib bossLib;

val _ = new_theory "rx_write_defs";

val NIC_DELTA_CPPI_RAM_WRITE_STEP_BD_PAs_defs = [
  rx_0receive_new_frame_lemmasTheory.rx_0receive_new_frame_cppi_ram_write_step_bd_pas_def,
  rx_1fetch_next_bd_lemmasTheory.rx_1fetch_next_bd_cppi_ram_write_step_bd_pas_def,
  rx_2issue_next_memory_write_request_lemmasTheory.rx_2issue_next_memory_write_request_cppi_ram_write_step_bd_pas_def,
  rx_3write_packet_error_lemmasTheory.rx_3write_packet_error_cppi_ram_write_step_bd_pas_def,
  rx_4write_rx_vlan_encap_lemmasTheory.rx_4write_rx_vlan_encap_cppi_ram_write_step_bd_pas_def,
  rx_5write_from_port_lemmasTheory.rx_5write_from_port_cppi_ram_write_step_bd_pas_def,
  rx_6write_eop_buffer_length_lemmasTheory.rx_6write_eop_buffer_length_cppi_ram_write_step_bd_pas_def,
  rx_7set_eop_eop_lemmasTheory.rx_7set_eop_eop_cppi_ram_write_step_bd_pas_def,
  rx_8set_eop_eoq_or_write_sop_buffer_offset_lemmasTheory.rx_8set_eop_eoq_or_write_sop_buffer_offset_cppi_ram_write_step_bd_pas_def,
  rx_9write_sop_buffer_offset_lemmasTheory.rx_9write_sop_buffer_offset_cppi_ram_write_step_bd_pas_def,
  rx_10write_sop_buffer_length_lemmasTheory.rx_10write_sop_buffer_length_cppi_ram_write_step_bd_pas_def,
  rx_11set_sop_sop_lemmasTheory.rx_11set_sop_sop_cppi_ram_write_step_bd_pas_def,
  rx_12write_sop_pass_crc_lemmasTheory.rx_12write_sop_pass_crc_cppi_ram_write_step_bd_pas_def,
  rx_13write_sop_long_lemmasTheory.rx_13write_sop_long_cppi_ram_write_step_bd_pas_def,
  rx_14write_sop_short_lemmasTheory.rx_14write_sop_short_cppi_ram_write_step_bd_pas_def,
  rx_15write_sop_mac_ctl_lemmasTheory.rx_15write_sop_mac_ctl_cppi_ram_write_step_bd_pas_def,
  rx_16write_sop_packet_length_lemmasTheory.rx_16write_sop_packet_length_cppi_ram_write_step_bd_pas_def,
  rx_17set_sop_eop_overrun_or_clear_sop_owner_and_hdp_lemmasTheory.rx_17set_sop_eop_overrun_or_clear_sop_owner_and_hdp_cppi_ram_write_step_bd_pas_def,
  rx_18clear_sop_owner_and_hdp_lemmasTheory.rx_18clear_sop_owner_and_hdp_cppi_ram_write_step_bd_pas_def,
  rx_19write_cp_lemmasTheory.rx_19write_cp_cppi_ram_write_step_bd_pas_def];

val NIC_DELTA_CPPI_RAM_WRITE_STEP_BD_PAs_CONJ_defs = save_thm (
  "NIC_DELTA_CPPI_RAM_WRITE_STEP_BD_PAs_CONJ_defs",
  LIST_CONJ NIC_DELTA_CPPI_RAM_WRITE_STEP_BD_PAs_defs);

val NIC_DELTA_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemmas = [
  rx_0receive_new_frame_lemmasTheory.rx_0receive_new_frame_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_1fetch_next_bd_lemmasTheory.rx_1fetch_next_bd_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_2issue_next_memory_write_request_lemmasTheory.rx_2issue_next_memory_write_request_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_3write_packet_error_lemmasTheory.rx_3write_packet_error_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_4write_rx_vlan_encap_lemmasTheory.rx_4write_rx_vlan_encap_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_5write_from_port_lemmasTheory.rx_5write_from_port_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_6write_eop_buffer_length_lemmasTheory.rx_6write_eop_buffer_length_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_7set_eop_eop_lemmasTheory.rx_7set_eop_eop_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_8set_eop_eoq_or_write_sop_buffer_offset_lemmasTheory.rx_8set_eop_eoq_or_write_sop_buffer_offset_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_9write_sop_buffer_offset_lemmasTheory.rx_9write_sop_buffer_offset_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_10write_sop_buffer_length_lemmasTheory.rx_10write_sop_buffer_length_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_11set_sop_sop_lemmasTheory.rx_11set_sop_sop_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_12write_sop_pass_crc_lemmasTheory.rx_12write_sop_pass_crc_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_13write_sop_long_lemmasTheory.rx_13write_sop_long_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_14write_sop_short_lemmasTheory.rx_14write_sop_short_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_15write_sop_mac_ctl_lemmasTheory.rx_15write_sop_mac_ctl_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_16write_sop_packet_length_lemmasTheory.rx_16write_sop_packet_length_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_17set_sop_eop_overrun_or_clear_sop_owner_and_hdp_lemmasTheory.rx_17set_sop_eop_overrun_or_clear_sop_owner_and_hdp_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_18clear_sop_owner_and_hdp_lemmasTheory.rx_18clear_sop_owner_and_hdp_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma,
  rx_19write_cp_lemmasTheory.rx_19write_cp_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemma];

val NIC_DELTA_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_CONJ_lemmas = save_thm (
  "NIC_DELTA_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_CONJ_lemmas",
  LIST_CONJ NIC_DELTA_WRITES_FIELDs_NOT_NDP_OF_BDs_IN_BD_QUEUE_lemmas);

val _ = export_theory();
